/*
 * This file is generated by jOOQ.
 */
package com.example.demo.shared.jooq.tables;


import com.example.demo.shared.jooq.Indexes;
import com.example.demo.shared.jooq.Keys;
import com.example.demo.shared.jooq.Public;
import com.example.demo.shared.jooq.tables.Users.UsersPath;
import com.example.demo.shared.jooq.tables.records.NotificationHistoriesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationHistories extends TableImpl<NotificationHistoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notification_histories</code>
     */
    public static final NotificationHistories NOTIFICATION_HISTORIES = new NotificationHistories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationHistoriesRecord> getRecordType() {
        return NotificationHistoriesRecord.class;
    }

    /**
     * The column <code>public.notification_histories.id</code>.
     */
    public final TableField<NotificationHistoriesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notification_histories.user_id</code>.
     */
    public final TableField<NotificationHistoriesRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.notification_histories.event_type</code>.
     */
    public final TableField<NotificationHistoriesRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.notification_histories.created_at</code>.
     */
    public final TableField<NotificationHistoriesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private NotificationHistories(Name alias, Table<NotificationHistoriesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NotificationHistories(Name alias, Table<NotificationHistoriesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.notification_histories</code> table
     * reference
     */
    public NotificationHistories(String alias) {
        this(DSL.name(alias), NOTIFICATION_HISTORIES);
    }

    /**
     * Create an aliased <code>public.notification_histories</code> table
     * reference
     */
    public NotificationHistories(Name alias) {
        this(alias, NOTIFICATION_HISTORIES);
    }

    /**
     * Create a <code>public.notification_histories</code> table reference
     */
    public NotificationHistories() {
        this(DSL.name("notification_histories"), null);
    }

    public <O extends Record> NotificationHistories(Table<O> path, ForeignKey<O, NotificationHistoriesRecord> childPath, InverseForeignKey<O, NotificationHistoriesRecord> parentPath) {
        super(path, childPath, parentPath, NOTIFICATION_HISTORIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class NotificationHistoriesPath extends NotificationHistories implements Path<NotificationHistoriesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> NotificationHistoriesPath(Table<O> path, ForeignKey<O, NotificationHistoriesRecord> childPath, InverseForeignKey<O, NotificationHistoriesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private NotificationHistoriesPath(Name alias, Table<NotificationHistoriesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public NotificationHistoriesPath as(String alias) {
            return new NotificationHistoriesPath(DSL.name(alias), this);
        }

        @Override
        public NotificationHistoriesPath as(Name alias) {
            return new NotificationHistoriesPath(alias, this);
        }

        @Override
        public NotificationHistoriesPath as(Table<?> alias) {
            return new NotificationHistoriesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTIFICATION_HISTORIES_EVENT_TYPE, Indexes.IDX_NOTIFICATION_HISTORIES_USER_ID);
    }

    @Override
    public UniqueKey<NotificationHistoriesRecord> getPrimaryKey() {
        return Keys.NOTIFICATION_HISTORIES_PKEY;
    }

    @Override
    public List<UniqueKey<NotificationHistoriesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NOTIFICATION_HISTORIES_USER_ID_EVENT_TYPE_KEY);
    }

    @Override
    public List<ForeignKey<NotificationHistoriesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NOTIFICATION_HISTORIES__NOTIFICATION_HISTORIES_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.NOTIFICATION_HISTORIES__NOTIFICATION_HISTORIES_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public NotificationHistories as(String alias) {
        return new NotificationHistories(DSL.name(alias), this);
    }

    @Override
    public NotificationHistories as(Name alias) {
        return new NotificationHistories(alias, this);
    }

    @Override
    public NotificationHistories as(Table<?> alias) {
        return new NotificationHistories(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationHistories rename(String name) {
        return new NotificationHistories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationHistories rename(Name name) {
        return new NotificationHistories(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationHistories rename(Table<?> name) {
        return new NotificationHistories(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotificationHistories where(Condition condition) {
        return new NotificationHistories(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotificationHistories where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotificationHistories where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotificationHistories where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotificationHistories where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotificationHistories where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotificationHistories where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NotificationHistories where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotificationHistories whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NotificationHistories whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
