/**
 * ============================================
 * 🎨 ButtonDanger (Figma Raw)
 * 📅 Generated at: 2025-11-12 JST
 * 🔗 Node ID: 185:852
 * 🔗 Figma URL: https://www.figma.com/design/WoOuJeIanK8Ke56zr6muug/Simple-Design-System--Community-?node-id=185-852
 * 📍 Implementation: features/shared/ui/atoms/ButtonDanger/ButtonDanger.tsx
 * ============================================
 *
 * This is the RAW version from Figma MCP - DO NOT USE IN PRODUCTION
 * Use ButtonDanger.tsx instead
 */
"use client";

import type React from "react";

const img =
  "http://localhost:3845/assets/1314e1c34290a8d8fd321f7729d2aeb463aa8dfc.svg";
const img1 =
  "http://localhost:3845/assets/01e8f9895a208f560b74743c2515c35c3d7487d3.svg";
const img2 =
  "http://localhost:3845/assets/fb95b70bc53ba96efc1c39114f9404923043eab6.svg";
const img3 =
  "http://localhost:3845/assets/492e0b9a07a0654405325201cf0df4cb60589b52.svg";
const img4 =
  "http://localhost:3845/assets/e948c761caa363127dbf081d49f02f77a8c1fa95.svg";
const img5 =
  "http://localhost:3845/assets/af356927da1b4a35792e5a5a5112915ed7ba4164.svg";
const img6 =
  "http://localhost:3845/assets/73a81e365f7a2657d7acbe3bcdcb4f9ec4909079.svg";

export interface ButtonDangerProps {
  className?: string;
}

export default function ButtonDanger({ className }: ButtonDangerProps) {
  return (
    <div data-name="Button Danger" data-node-id="185:852">
      <div
        className={`
          bg-[var(--sds-color-background-danger-default,#ec221f)]
          border-[var(--sds-color-border-danger-secondary,#c00f0c)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
          ${className}
        `}
        data-name="Variant=Primary, State=Default, Size=Medium"
        data-node-id="185:865"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-300,12px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="185:866"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I185:866;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-danger-on-danger,#fee9e7)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="185:867"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="185:868"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I185:868;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img1} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-danger-hover,#c00f0c)]
          border-[var(--sds-color-border-danger-default,#900b09)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Primary, State=Hover, Size=Medium"
        data-node-id="185:873"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-300,12px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="185:874"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I185:874;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-danger-on-danger,#fee9e7)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="185:875"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="185:876"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I185:876;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img1} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          box-border
          content-stretch
          flex
          gap-[var(--sds-size-space-200,8px)]
          items-center
          justify-center
          overflow-clip
          p-[var(--sds-size-space-300,12px)]
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Subtle, State=Default, Size=Medium"
        data-node-id="185:949"
      >
        <div
          className={`
            overflow-clip
            relative
            shrink-0
            size-[16px]
          `}
          data-name="Star"
          data-node-id="185:950"
        >
          <div
            className={`
              absolute
              inset-[8.33%_8.33%_12.42%_8.33%]
            `}
            data-name="Icon"
            data-node-id="I185:950;68:16010"
          >
            <div
              className={`
                absolute
                inset-[-6.31%_-6%]
              `}
              style={
                {
                  "--stroke-0": "rgba(144, 11, 9, 1)",
                } as React.CSSProperties
              }
            >
              <img alt="" className="block max-w-none size-full" src={img2} />
            </div>
          </div>
        </div>
        <p
          className={`
            font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
            font-[var(--sds-typography-body-font-weight-regular,400)]
            leading-none
            not-italic
            relative
            shrink-0
            text-[color:var(--sds-color-text-danger-default,#900b09)]
            text-[length:var(--sds-typography-body-size-medium,16px)]
            text-nowrap
            whitespace-pre
          `}
          data-node-id="185:951"
        >
          Button
        </p>
        <div
          className={`
            overflow-clip
            relative
            shrink-0
            size-[16px]
          `}
          data-name="X"
          data-node-id="185:952"
        >
          <div
            className={`
              absolute
              inset-1/4
            `}
            data-name="Icon"
            data-node-id="I185:952;68:16114"
          >
            <div
              className={`
                absolute
                inset-[-10%]
              `}
              style={
                {
                  "--stroke-0": "rgba(144, 11, 9, 1)",
                } as React.CSSProperties
              }
            >
              <img alt="" className="block max-w-none size-full" src={img3} />
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-danger-tertiary-hover,#fdd3d0)]
          border-[var(--sds-color-border-danger-default,#900b09)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Subtle, State=Hover, Size=Medium"
        data-node-id="185:957"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-300,12px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="185:958"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I185:958;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(144, 11, 9, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img2} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-danger-default,#900b09)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="185:959"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="185:960"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I185:960;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(144, 11, 9, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img3} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-danger-default,#ec221f)]
          border-[var(--sds-color-border-danger-secondary,#c00f0c)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Primary, State=Default, Size=Small"
        data-node-id="185:977"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-200,8px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="185:978"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I185:978;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-danger-on-danger,#fee9e7)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="185:979"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="185:980"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I185:980;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img4} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-danger-hover,#c00f0c)]
          border-[var(--sds-color-border-danger-default,#900b09)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Primary, State=Hover, Size=Small"
        data-node-id="185:985"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-200,8px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="185:986"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I185:986;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-danger-on-danger,#fee9e7)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="185:987"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="185:988"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I185:988;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(254, 233, 231, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img1} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          box-border
          content-stretch
          flex
          gap-[var(--sds-size-space-200,8px)]
          items-center
          justify-center
          overflow-clip
          p-[var(--sds-size-space-200,8px)]
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Subtle, State=Default, Size=Small"
        data-node-id="185:1061"
      >
        <div
          className={`
            overflow-clip
            relative
            shrink-0
            size-[16px]
          `}
          data-name="Star"
          data-node-id="185:1062"
        >
          <div
            className={`
              absolute
              inset-[8.33%_8.33%_12.42%_8.33%]
            `}
            data-name="Icon"
            data-node-id="I185:1062;68:16010"
          >
            <div
              className={`
                absolute
                inset-[-6.31%_-6%]
              `}
              style={
                {
                  "--stroke-0": "rgba(144, 11, 9, 1)",
                } as React.CSSProperties
              }
            >
              <img alt="" className="block max-w-none size-full" src={img2} />
            </div>
          </div>
        </div>
        <p
          className={`
            font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
            font-[var(--sds-typography-body-font-weight-regular,400)]
            leading-none
            not-italic
            relative
            shrink-0
            text-[color:var(--sds-color-text-danger-default,#900b09)]
            text-[length:var(--sds-typography-body-size-medium,16px)]
            text-nowrap
            whitespace-pre
          `}
          data-node-id="185:1063"
        >
          Button
        </p>
        <div
          className={`
            overflow-clip
            relative
            shrink-0
            size-[16px]
          `}
          data-name="X"
          data-node-id="185:1064"
        >
          <div
            className={`
              absolute
              inset-1/4
            `}
            data-name="Icon"
            data-node-id="I185:1064;68:16114"
          >
            <div
              className={`
                absolute
                inset-[-10%]
              `}
              style={
                {
                  "--stroke-0": "rgba(144, 11, 9, 1)",
                } as React.CSSProperties
              }
            >
              <img alt="" className="block max-w-none size-full" src={img3} />
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-danger-tertiary-hover,#fdd3d0)]
          border-[var(--sds-color-border-danger-default,#900b09)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Subtle, State=Hover, Size=Small"
        data-node-id="185:1069"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-200,8px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="185:1070"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I185:1070;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(144, 11, 9, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img2} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-danger-default,#900b09)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="185:1071"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="185:1072"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I185:1072;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(144, 11, 9, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img3} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-disabled-default,#d9d9d9)]
          border-[var(--sds-color-border-disabled-default,#b3b3b3)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Primary, State=Disabled, Size=Medium"
        data-node-id="196:10059"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-300,12px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="196:10060"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I196:10060;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img5} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-disabled-on-disabled,#b3b3b3)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="196:10061"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="196:10062"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I196:10062;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img6} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-disabled-default,#d9d9d9)]
          border-[var(--sds-color-border-disabled-default,#b3b3b3)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Subtle, State=Disabled, Size=Medium"
        data-node-id="196:10071"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-300,12px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="196:10072"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I196:10072;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img5} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-disabled-default,#b3b3b3)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="196:10073"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="196:10074"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I196:10074;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img6} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-disabled-default,#d9d9d9)]
          border-[var(--sds-color-border-disabled-default,#b3b3b3)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Primary, State=Disabled, Size=Small"
        data-node-id="196:10075"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-200,8px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="196:10076"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I196:10076;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img5} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-disabled-on-disabled,#b3b3b3)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="196:10077"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="196:10078"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I196:10078;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img6} />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        className={`
          bg-[var(--sds-color-background-disabled-default,#d9d9d9)]
          border-[var(--sds-color-border-disabled-default,#b3b3b3)]
          border-[var(--sds-size-stroke-border,1px)]
          border-solid
          relative
          rounded-[var(--sds-size-radius-200,8px)]
          size-full
        `}
        data-name="Variant=Subtle, State=Disabled, Size=Small"
        data-node-id="196:10087"
      >
        <div
          className={`
            box-border
            content-stretch
            flex
            gap-[var(--sds-size-space-200,8px)]
            items-center
            justify-center
            overflow-clip
            p-[var(--sds-size-space-200,8px)]
            relative
            rounded-[inherit]
            size-full
          `}
        >
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="Star"
            data-node-id="196:10088"
          >
            <div
              className={`
                absolute
                inset-[8.33%_8.33%_12.42%_8.33%]
              `}
              data-name="Icon"
              data-node-id="I196:10088;68:16010"
            >
              <div
                className={`
                  absolute
                  inset-[-6.31%_-6%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img5} />
              </div>
            </div>
          </div>
          <p
            className={`
              font-[family-name:var(--sds-typography-body-font-family,'Inter:Regular',sans-serif)]
              font-[var(--sds-typography-body-font-weight-regular,400)]
              leading-none
              not-italic
              relative
              shrink-0
              text-[color:var(--sds-color-text-disabled-default,#b3b3b3)]
              text-[length:var(--sds-typography-body-size-medium,16px)]
              text-nowrap
              whitespace-pre
            `}
            data-node-id="196:10089"
          >
            Button
          </p>
          <div
            className={`
              overflow-clip
              relative
              shrink-0
              size-[16px]
            `}
            data-name="X"
            data-node-id="196:10090"
          >
            <div
              className={`
                absolute
                inset-1/4
              `}
              data-name="Icon"
              data-node-id="I196:10090;68:16114"
            >
              <div
                className={`
                  absolute
                  inset-[-10%]
                `}
                style={
                  {
                    "--stroke-0": "rgba(179, 179, 179, 1)",
                  } as React.CSSProperties
                }
              >
                <img alt="" className="block max-w-none size-full" src={img6} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
