platform:
  ios:
    snapshotKeyHonorModalViews: false
    disableAnimations: true
  android:
    disableAnimations: true
hooks:
  onFlowStart:
    - runCommand:
        command:
          - bash
          - -lc
          - ./e2e/scripts/reset_backend.sh
