apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  sources:
    # Official Metabase Helm Chart
    - repoURL: https://pmint93.github.io/helm-charts
      chart: metabase
      targetRevision: 2.14.0
      helm:
        valueFiles:
          - $values/infra/cd/metabase/values.yaml
    # Values from this repo
    - repoURL: https://github.com/d-kanai/awesome-template.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: awesome-template
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
