apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: web-security-sast
  namespace: default
spec:
  description: "Semgrep - 静的解析セキュリティスキャン"
  workspaces:
    - name: source
      description: "クローン済みソースコード"
  steps:
    - name: semgrep-scan
      image: semgrep/semgrep:latest
      workingDir: $(workspaces.source.path)/source/frontend_web
      script: |
        #!/bin/sh
        semgrep scan --config auto --severity WARNING --error --verbose .
