package com.example.demo.testsupport;

import com.example.demo.shared.auth0.Auth0ClientInterface;
import com.example.demo.shared.auth0.Auth0UserInfo;
import com.example.demo.shared.security.customer.CustomerJwtTokenProvider;
import org.jspecify.annotations.Nullable;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;

/**
 * Test configuration for Auth0Client.
 *
 * <p>Provides a mock Auth0Client that decodes JWT tokens generated by CustomerJwtTokenProvider for
 * testing purposes. This allows existing tests to continue using JWT tokens while the production
 * code uses Auth0 opaque tokens.
 */
@Configuration
public class TestAuth0ClientConfig {

  @Bean
  @Primary
  public Auth0ClientInterface testAuth0Client(final CustomerJwtTokenProvider jwtTokenProvider) {
    return new TestAuth0Client(jwtTokenProvider);
  }

  /** Mock Auth0Client that validates tokens using CustomerJwtTokenProvider. */
  public static class TestAuth0Client implements Auth0ClientInterface {

    private final CustomerJwtTokenProvider jwtTokenProvider;

    public TestAuth0Client(final CustomerJwtTokenProvider jwtTokenProvider) {
      this.jwtTokenProvider = jwtTokenProvider;
    }

    @Override
    public @Nullable Auth0UserInfo getUserInfo(final String accessToken) {
      try {
        if (jwtTokenProvider.validateToken(accessToken)) {
          final String userId = jwtTokenProvider.getUserIdFromToken(accessToken);
          final String email = jwtTokenProvider.getEmailFromToken(accessToken);
          return new Auth0UserInfo(userId, email);
        }
        return null;
      } catch (final Exception e) {
        return null;
      }
    }
  }
}
