/*
 * This file is generated by jOOQ.
 */
package com.example.demo.shared.jooq;

import com.example.demo.shared.jooq.tables.FlywaySchemaHistory;
import com.example.demo.shared.jooq.tables.Users;
import com.example.demo.shared.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.example.demo.shared.jooq.tables.records.UsersRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/** A class modelling foreign key relationships and constraints of tables in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK =
      Internal.createUniqueKey(
          FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
          DSL.name("flyway_schema_history_pk"),
          new TableField[] {FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK},
          true);
  public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY =
      Internal.createUniqueKey(
          Users.USERS, DSL.name("users_email_key"), new TableField[] {Users.USERS.EMAIL}, true);
  public static final UniqueKey<UsersRecord> USERS_PKEY =
      Internal.createUniqueKey(
          Users.USERS, DSL.name("users_pkey"), new TableField[] {Users.USERS.ID}, true);
}
