spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demo
    password: demo123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    placeholders:
      create_pgcrypto_extension: 'CREATE EXTENSION IF NOT EXISTS "pgcrypto";'
      users_id_uuid_clause: ' DEFAULT gen_random_uuid()'

server:
  port: 8080
