spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demo
    password: demo123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

server:
  port: 8080
