spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jooq:
    sql-dialect: H2

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    org.springframework.boot.web.embedded.tomcat: INFO
    com.example.demo: INFO
