spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: demo
    password: demo123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    placeholders:
      create_pgcrypto_extension: 'CREATE EXTENSION IF NOT EXISTS "pgcrypto";'
      drop_users_id_sequence: 'DROP SEQUENCE IF EXISTS users_id_seq;'
      users_id_uuid_type: 'TYPE UUID USING gen_random_uuid()'
      users_id_uuid_default: 'gen_random_uuid()'

server:
  port: 8080
