/*
 * This file is generated by jOOQ.
 */
package com.example.demo.shared.jooq.tables.records;


import com.example.demo.shared.jooq.tables.NotificationHistories;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationHistoriesRecord extends UpdatableRecordImpl<NotificationHistoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notification_histories.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification_histories.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.notification_histories.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification_histories.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.notification_histories.event_type</code>.
     */
    public void setEventType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification_histories.event_type</code>.
     */
    public String getEventType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.notification_histories.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification_histories.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.notification_histories.event_id</code>.
     */
    public void setEventId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification_histories.event_id</code>.
     */
    public UUID getEventId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationHistoriesRecord
     */
    public NotificationHistoriesRecord() {
        super(NotificationHistories.NOTIFICATION_HISTORIES);
    }

    /**
     * Create a detached, initialised NotificationHistoriesRecord
     */
    public NotificationHistoriesRecord(UUID id, UUID userId, String eventType, LocalDateTime createdAt, UUID eventId) {
        super(NotificationHistories.NOTIFICATION_HISTORIES);

        setId(id);
        setUserId(userId);
        setEventType(eventType);
        setCreatedAt(createdAt);
        setEventId(eventId);
        resetChangedOnNotNull();
    }
}
