/*
 * This file is generated by jOOQ.
 */
package com.example.demo.shared.jooq.tables.records;

import com.example.demo.shared.jooq.tables.Users;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.users.id</code>. */
  public void setId(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.users.id</code>. */
  public UUID getId() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.users.email</code>. */
  public void setEmail(String value) {
    set(1, value);
  }

  /** Getter for <code>public.users.email</code>. */
  public String getEmail() {
    return (String) get(1);
  }

  /** Setter for <code>public.users.password</code>. */
  public void setPassword(String value) {
    set(2, value);
  }

  /** Getter for <code>public.users.password</code>. */
  public String getPassword() {
    return (String) get(2);
  }

  /** Setter for <code>public.users.created_at</code>. */
  public void setCreatedAt(LocalDateTime value) {
    set(3, value);
  }

  /** Getter for <code>public.users.created_at</code>. */
  public LocalDateTime getCreatedAt() {
    return (LocalDateTime) get(3);
  }

  /** Setter for <code>public.users.updated_at</code>. */
  public void setUpdatedAt(LocalDateTime value) {
    set(4, value);
  }

  /** Getter for <code>public.users.updated_at</code>. */
  public LocalDateTime getUpdatedAt() {
    return (LocalDateTime) get(4);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached UsersRecord */
  public UsersRecord() {
    super(Users.USERS);
  }

  /** Create a detached, initialised UsersRecord */
  public UsersRecord(
      UUID id, String email, String password, LocalDateTime createdAt, LocalDateTime updatedAt) {
    super(Users.USERS);

    setId(id);
    setEmail(email);
    setPassword(password);
    setCreatedAt(createdAt);
    setUpdatedAt(updatedAt);
    resetChangedOnNotNull();
  }
}
